scheduledItems.push({
  id: task.id,
  type: itemType,
  name: task.name,
  duration: duration,
  startTime: localStart,
  endTime: localEnd,
  emoji: assignEmoji(task.name),
  description: isBreak ? getBreakDescription(duration) : undefined,
  isTimedEvent: true,
  isCritical: task.is_critical,
  isFlexible: task.is_flexible,
  isLocked: task.is_locked,
  energyCost: task.energy_cost,
  isCompleted: task.is_completed,
  isCustomEnergyCost: task.is_custom_energy_cost,
});