completedScheduledTasks={completedTasksForSelectedDayList.map(ct => ({
  id: ct.id,
  user_id: ct.user_id,
  name: ct.task_name,
  break_duration: null,
  start_time: null,
  end_time: null,
  scheduled_date: ct.original_scheduled_date || selectedDay,
  created_at: ct.created_at,
  updated_at: ct.created_at,
  is_critical: ct.is_critical,
  is_flexible: true,
  is_locked: false,
  energy_cost: ct.energy_cost,
  is_completed: true,
  is_custom_energy_cost: false,
})) as DBScheduledTask[]}